name: La mera verdura

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  greeting:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Where am I?"
        run: pwd
      - name: "Who am I?"
        run: whoami
      - run: touch lockfile
      - name: "List all the files"
        run: ls -la

      - uses: actions/upload-artifact@v4
        with:
          name: lockmadafakingfile
          path: lockfile.lock
  
  check:
    needs: greeting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: lockmadafakingfile
      - name: "List all the files before checkout"
        run: ls -la
      - uses: actions/checkout@v4

      - name: "List all the files after checkout"
        run: ls -la

