name: La mera verdura

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  greeting:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Where am I?"
        run: pwd
      - name: "Who am I?"
        run: whoami
      - name: "List all the files"
        run: ls -la

