name: La mera verdura push

on:
  push:
    branches: [ "infra" ]
jobs:

  validation:

    runs-on: ubuntu-latest

    steps:
    - name: Print ref
      run: |
        echo 'Ref: ${{ github.ref }}'
        echo 'Ref name: ${{ github.ref_name }}'
        echo 'Ref type: ${{ github.ref_type }}'
        echo 'Ref protected: ${{ github.ref_protected }}'
        echo 'Base ref: ${{ github.ref }}'